version: '2'
services:
    megasync:
        build: .
        container_name: megasync
        privileged: true
        volumes:
            - /config:/config
            - /home/kyle/no_snapshot/snapshots:/snapshots
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro