version: '2'
services:
    rsnapshot:
        # https://bitbucket.org/scandio/docker-rsnapshot
        # https://hub.docker.com/r/scandio/rsnapshot/
        container_name: rsnapshot
        image: "scandio/rsnapshot"
        volumes:
            - ./rsnapshot/config:/config
            - ./rsnapshot/target:/target
            - /:/source:ro
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        environment:
            SNAPSHOT_TYPE: "${SNAPSHOT_TYPE}"
    megautils:
        build: ./megautils
        container_name: megautils
        privileged: true
        volumes:
            - ./megautils/config:/config
            - ./rsnapshot/target:/snapshots
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        environment:
            HOSTNAME: "${COMMON_HOST}"
            MEGAUSER: "${MEGAUSER}"
            MEGAPASS: "${MEGAPASS}"