version: '2'
services:
    megasync:
        build: .
        container_name: megasync
        privileged: true
        volumes:
            - /home/kyle/.docker/volumes/megasync/config:/config
            - /home/kyle/.docker/volumes/rsnapshot/target:/snapshots
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro